# Generated by Django 5.0.6 on 2024-06-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='vpn_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
